language: ruby
cache: bundler
rvm:
  - 2.7
before_install:
  - gem install bundler
script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - croitoruradubogdan@gmail.com
    on_failure: change
    on_success: never
